Console.WriteLine("Введите координаты для точки x");
int xa = Convert.ToInt32(Console.ReadLine());
int xb = Convert.ToInt32(Console.ReadLine());
int xc = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координаты для точки y");
int ya = Convert.ToInt32(Console.ReadLine());
int yb = Convert.ToInt32(Console.ReadLine());
int yc = Convert.ToInt32(Console.ReadLine());
double dist = Convert.ToDouble(Math.Round(Math.Sqrt(Math.Pow((xa - ya), 2) + Math.Pow((xb - yb), 2) + Math.Pow((xc - yc), 2)), 2));
Console.WriteLine($"Расстояние между точками x  и y на оси координат в 3D пространстве равно {dist}");